- hosts: localhost
  vars:
    zuul_log_url: "http://logs.example.org"
  roles:
    - emit-job-header

  tasks:
    - name: Return log URL to Zuul
      zuul_return:
        data:
          zuul:
            log_url: "{{ zuul_log_url }}/{{ zuul_log_path }}/"

- hosts: all
  pre_tasks:
    # NOTE(pabelanger): Until we hit the validate-host role, we have a minimal
    # set of ansible variables collected by zuul-executor. This doesn't include
    # network variables (ansible_default_ipv4 / ansible_default_ipv6) so gather
    # these variables as they are important to the configure-unbound role.
    - name: Gather network facts
      setup:
        gather_subset: 'network'

  roles:
    - add-build-sshkey
    - prepare-workspace
